import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode, FC } from 'react';
import clsx from 'clsx';
import NextThemeProvider from '@/providers/next-theme-provider';
import NextAuthProvider from '@/providers/next-auth-provider';
import GlobalState from '@/contexts/global-context';

// Inicializace fontu Inter
const inter = Inter({ subsets: ['latin'] });

// Metadata pro aplikaci
export const metadata: Metadata = {
  // Titulek stránky
  title: 'Create Next App',
  // Popis stránky
  description: 'Generated by create next app',
};

// Rozhraní pro props komponenty RootLayout
interface RootLayoutProps {
  // Potomci, kteří budou obaleni layoutem
  children: ReactNode;
}

// Komponenta nastavuje strukturu HTML stránky a poskytuje kontextové providery
const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'antialiased')}>
        {/* Poskytovatel témat */}
        <NextThemeProvider>
          {/* Poskytovatel autentizace */}
          <NextAuthProvider>
            {/* Poskytovatel globálního stavu */}
            <GlobalState>{children}</GlobalState>
          </NextAuthProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
